;WRITE A PROGRAM TO FIND THE LARGEST AND SMALLEST NUMBER IN GIVEN ARRAY
INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA
ARR DB 4,3,8,2,6
.CODE
MAIN PROC  
    MOV AX,@DATA
    MOV DS,AX
    MOV SI,OFFSET ARR
    MOV CX,5  
    MOV BL,[SI]
    L:
    CMP [SI],BL
    JLE SMALL  
    COMPARE:
    INC SI
    LOOP L 
    PRINT "Smallest value in Array is :" 
    MOV DL,BL
    ADD DL,48
    MOV AH,2
    INT 21H
    SMALL:
    MOV BL,[SI] 
    JMP COMPARE
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN