;PROGRAM TO SORT ARRAY IN DECENDING  ORDER       
INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA
ARR DB 5 DUP(?)
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV CX,5
    MOV BX,OFFSET ARR  
    PRINT 'ENTER 5 NUMBER IN ARRAY :'
    CALL ENTKEY
    INPUTS:
    MOV AH,1
    INT 21H
    MOV [BX],AL
    INC BX
    LOOP INPUTS
    
    MOV CX,5
    DEC CX
    OUTERLOOP:
    MOV BX,CX
    MOV SI,0
    COMLOOP:
    MOV AL,ARR[SI]
    MOV DL,ARR[SI+1]
    CMP AL,DL
    ;IF CARRY NOT OCCUR THEN JUMP TO NO SWAP
    JNC NOSWAP
    MOV ARR[SI],DL
    MOV ARR[SI+1],AL
    NOSWAP:
    INC SI
    DEC BX
    JNZ COMLOOP
    LOOP OUTERLOOP 
    CALL ENTKEY
    PRINT 'AFTER DECENDING SORT THE ARRAY IS :'
    CALL ENTKEY
    MOV BX,OFFSET ARR
    MOV CX,5
    OUTPUTS:
    MOV DL,[BX]
    MOV AH,2
    INT 21H
    INC BX
    ;FOR GIVING SPACE B/W DIGIT
    MOV DL,32
    MOV AH,2
    INT 21H
    LOOP OUTPUTS
    MOV AH,4CH
    INT 21H
      
   
    MAIN ENDP 
ENTKEY PROC
    MOV DL,10
    MOV AH,2
    INT 21H
    MOV DL,13
    MOV AH,2
    INT 21H
    RET 
    ENTKEY ENDP
END MAIN
    