;CREATE TABLE THAT THE USER ENTER NUMBER.
.MODEL SMALL
.STACK 100H
.DATA    
MSG DB "ENTER A NUMBER :$"    
STRING DB 5 DUP(?)    
NUM DB ?
.CODE
MAIN PROC   
    MOV AX,@DATA
    MOV DS,AX
    LEA DX,MSG
    MOV AH,9
    INT 21H 
    
    MOV AH,1    ;GETS DIGITS AS A CHARACTER
    INT 21H
    SUB AL,48   ;CONVERT CHARACTER INTO NUMBER
    MOV NUM,AL
    
    XOR BX,BX
    MOV BL,1
    MOV CX,10
    TOP:
    MOV AL,NUM
    MUL BL
    PUSH BX
    PUSH CX   ;RESERVING BX AND CX FOR LATER USE BY PUSHING STACK  ;
    LEA SI,STRING
    MOV BX,10 ;STOTING 2 DIGITS NUMBERS AS CHARACTER IN STRING
    XOR CX,CX
    
    DIVISION:
    XOR DX,DX
    DIV BX
    PUSH DX 
    INC CX
    CMP AX,0
    JNE DIVISION
    STORE:
    POP DX 
    ADD DL,48
    MOV [SI],DL
    INC SI
    LOOP STORE
    
    MOV [SI],'$'
    POP CX
    POP BX
    MOV DL,10
    MOV AH,2
    INT 21H
    MOV DL,13
    MOV AH,2
    INT 21H
    
    LEA DX,STRING    ;GET THAT 2 DIGIT NUMBER WHICH IS CHARACTER  FROM STRING
     MOV AH,9
    INT 21H
    INC BL
    LOOP TOP  ;;MULTIPLICATION TABLE STOPS
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN