;PROGRAM TO CAL THE FACTORIAL OF THE NUMBER
.MODEL SMALL
.STACK 100H
.DATA
ANS DB ?
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV AL,5
    MOV CL,4
    MOV BL,AL
    SUB BL,1
    L:
     MUL BL    ; MUL BL=AL=AL*BL  THE RESULT WILL STORE IN AL REGISTER
     SUB BL,1
    LOOP L
    MOV ANS,AL  
    MOV DL,ANS 
    add dl,48
    MOV AH,2
  ;4CH
    INT 21H
    MAIN ENDP
END MAIN