;AC CODE WITH NOMI
.MODEL SMALL
.STACK 100H       
.DATA
ISON DB ? ;VAR USED FOR CHK MODE ON=1 OR OFF=0
TEMP DB ?
TAR_TEM DB 9
ON DB 10,13,'THE AC IS TURNED ON...!!$'
OFF DB 10,13,'THE AC IS TURNED OFF...!!$'
MSGTEM DB 10,13,'THE CURRENT TEMPERATURE IS :$' 
MSGTARGET DB 10,13,'THE TARGET TEMPERATURE IS :$'
MSGADJUST DB 10,13,'ADJUST TEMPERATUE...!!$'
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    MOV ISON,1
    MOV DX,OFFSET ON
    MOV AH,9
    INT 21H
    
    MOV TEMP,8
    
    MOV DX,OFFSET MSGTEM
    MOV AH,9
    INT 21H
    
    MOV AL,TEMP
    ADD AL,30H
    MOV DL,AL
    MOV AH,2
    INT 21H
    
    LEA DX,MSGTARGET
    MOV AH,9
    INT 21H
    
    MOV AL,TAR_TEM
    ADD AL,30H
    MOV DL,AL
    MOV AH,2
    INT 21H
    
    LEA DX,MSGADJUST
    MOV AH,9
    INT 21H
    
    MOV ISON,0
    MOV DX,OFFSET OFF
    MOV AH,9
    INT 21H
    MOV AH,4CH
    INT 21H
    MAIN ENDP
ENDP MAIN

