;WASHING MACHINE CODE BY NOMI
.MODEL SMALL
.STACK 100H
.DATA
PROMPT DB 10,13,'PLEASE ENTER A PROMPT WASHING MODE (1 FOR NORMAL AND 2 FOR GENTLE):$'
MODE DB ?                ;VAR FOR STORING THE MODE OF WASHING MACHINE
NORMAL_MODE DB 10,13,'PERFORMING WASHING IN NORMAL MODE...!!$'
GENTLE_MODE DB 10,13,'PERFORMING WASHING IN GENTLE MODE...!!$' 
INVALID_PRO DB 10,13,'INVALID PROMPT PLEASE ENTER 1 FOR NORMAL AND 2 FRO GENTLE :$'
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    ;SHOW PROMPT MSG ON CONSOLE WINDOW
    MOV DX,OFFSET PROMPT
    MOV AH,9
    INT 21H
    ;INSTRUCTION FOR ENTERING CHOICE
    MOV AH,1
    INT 21H
    SUB AL,'0' ;CONVERT ASCII VALUE TO DIGIT
    MOV MODE,AL
    
    ;NOW COMPARINSON HERE OF MODE SELECTED
    CMP MODE,1
    JE NOR_MODE
    CMP MODE,2
    JE GEN_MODE
    
    ;INVALID MODE ENTER
    MOV DX,OFFSET INVALID_PRO
    MOV AH,9
    INT 21H
    JMP EXIT 
    
    GEN_MODE:
    MOV DX,OFFSET GENTLE_MODE
    MOV AH,9
    INT 21H
    JMP EXIT 
    
    NOR_MODE:
    MOV DX,OFFSET NORMAL_MODE
    MOV AH,9
    INT 21H 
    EXIT:
    MOV AH,4CH
    INT 21H
       
    
    
    
    MAIN ENDP
END MAIN